# Donation channels for TextAid
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [kenny516]
custom:
  - https://www.buymeacoffee.com/kenny516
  - https://ko-fi.com/kenny516
